### ISSUE TITLE
Update firmware to latest stable Marlin v2.x.x

### ISSUE THREAD

**Issue by zas** [Eryone/mega2560#4]
Current firmware is based on Marlin v2.0.0 apparently, but most recent Marlin v2 release is v2.0.7 as today.

**Comment by NightHammer1000** [comment]
I am on it. Will be up either today or tomorrow after some testing. You can find the WIP in my fork. 
Stock only. I don't have any Autoleveling stuff to test those configs.

**Comment by zas** [comment]
BTW, I tried to diff current firmware source with official Marlin, but that's a pain because Eryone team didn't actually fork Marlin but rather copied over, plus didn't do clean and commented commits. What's a pity.

**Comment by NightHammer1000** [comment]
Update is done. Took a bit longer than expected.

Had to set up a whole new Repo for it because Eryone changed so much, even Text in the Comments, that every Merge attempt went south real fast.

So I basicly took a stock Marlin 2.0.x_Bugfix and build a Config for it. With a few small Adjustment. 
Including:

1. Got rid of Classic Jerk and switched to Junction Deviation to hopefully get rid of the X-Shifting on my Machine.
2. Changed form Mesh Bed Leveling to UBL with Manual Probing.
3. Set the Probe Position as the Actual Nozzle itself.
4. Kept the PIDTemp for Bed disabled to keep PSU from Reseting.
5. Actually set the Stepper Driver Type in the Config to "TMC2208_STANDALONE" so the use the Optimal Advanced Values.
6. They also for some god forsaken reason changed pins in the RAMBO definition. So i created a new Board Definition called "BOARD_THINKER_RAMBO". Updating would be impossible otherwhise.
7. PID Tune the Hotend at 230° with 10 Cycles and Part Cooling FAN at 100%
7. And a few other small things.

Testprint is currently running.
https://github.com/NightHammer1000/Marlin_ThinkerSE

@eryone You are free to Fork this Repo. This format makes it easy to Update it because you can just merge it with the Marlin Upstream.

**Comment by NightHammer1000** [comment]
Also posted here
https://www.eryone.com/forum/viewtopic.php?f=21&t=315

**Comment by bryanpedini** [comment]
>     6. They also for some god forsaken reason changed pins in the RAMBO definition. So i created a new Board Definition called "BOARD_THINKER_RAMBO". Updating would be impossible otherwhise.

They did **WHAT**?? [madness link](https://github.com/MarlinFirmware/Configurations/issues/356) ([specifically](https://github.com/MarlinFirmware/Configurations/issues/356#issuecomment-756431966))

That's the stupid reason why I don't get the LCD knob turning on my board. Basically `#define BOARD BOARD_RAMBO` is (technically) wrong then!

**Comment by bryanpedini** [comment]
Board is being added here: [MarlinFirmware/Marlin](https://github.com/MarlinFirmware/Marlin/pull/20727), while it's default (stock) config it's available here: [MarlinFirmware/Configurations](https://github.com/MarlinFirmware/Configurations/pull/395).

This will be taken on from the Marlin contributors, as new features get introduced to the upstream the configurations will be updated as well, also, from my understanding the board definition is made of only the changes between the original `RAMBO` and the differential with `RAMBO_THINKERV2` I haave created (link above), so that should be taken care too.

For Eryone developers/employees: if anything more is added/needed, you should be able to create an Is/PR on the two base repos linked above, like `RAMBO_THINKERV2.1` for a new board revision for example. If you're not able/capable of creating issues / PRs, Google a tutorial, or quit using GitHub 😄 (seriously tho, Google it, it's 3yo-easy).

PS: I think this can be closed, as of now and as noted before, new firmware releases + configuration now **should** be taken care by the official Marlin maintainers. Also, I ported over the stock configuration because that's what I have, I'll also work to port over the BLTOUCH version since I just ordered one; if you have any expertise in `diff`ing two files and making a PR, feel free to add TMC2209 and other configs too!
